# Generated by Django 3.0.6 on 2020-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
