# Generated by Django 3.0.6 on 2020-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_slide_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='link_text',
            field=models.CharField(blank=True, max_length=256, verbose_name='Текст кнопки'),
        ),
    ]
