# Generated by Django 3.0.6 on 2020-09-04 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_auto_20200903_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=128, verbose_name='Ф.И.О.')),
                ('customer_phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('customer_email', models.CharField(max_length=128, verbose_name='Email')),
                ('customer_city', models.CharField(max_length=128, verbose_name='Город')),
                ('customer_address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('payment_type', models.CharField(max_length=128, verbose_name='Способ оплаты')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создание заказа')),
                ('status', models.CharField(default='Не оплачен', max_length=128, verbose_name='Статус')),
                ('delivery', models.BooleanField(default=True, verbose_name='Доставка')),
                ('products_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость товаров')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость доставки')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость товара на момент заказа')),
                ('delivery_price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки')),
                ('casing', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Casing', verbose_name='Обивка')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Color', verbose_name='Цвет ножек')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
