# Generated by Django 3.0.6 on 2020-08-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200824_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bed_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина спального места, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bed_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина спального места, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бельевой ящик, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер в разложенном виде, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем, куб. м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина, см'),
        ),
    ]
