# Generated by Django 3.0.6 on 2020-08-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200824_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category', verbose_name='Категория')),
                ('mechanism', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Mechanism', verbose_name='Механизм')),
            ],
        ),
    ]
