# Generated by Django 3.0.6 on 2020-08-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorymechanism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymechanism',
            name='category',
        ),
        migrations.AddField(
            model_name='categorymechanism',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='products.Category', verbose_name='Категория'),
        ),
    ]
