# Generated by Django 3.0.6 on 2020-08-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200825_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymechanism',
            name='category',
        ),
        migrations.AddField(
            model_name='categorymechanism',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category', verbose_name='Категория'),
        ),
    ]
