# Generated by Django 3.0.6 on 2020-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200825_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delivery_price',
            field=models.IntegerField(blank=True, default=1000, verbose_name='Стоимость доставки'),
            preserve_default=False,
        ),
    ]
