# Generated by Django 3.0.6 on 2020-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200903_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lift_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость подъема'),
        ),
    ]
